### ISSUE TITLE
Design of the urdf model of the left_hand_mk3 seems different from the real design

### ISSUE THREAD

**Issue by gabrielecaddeo** [robotology/icub-models#104]
Hi,
I am working with the urdf model of the `left_hand_mk3`.  While working with it I noticed that there is something strange going on with the thumb opposition joint.

As you can see in the following
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/49904924/132924995-5174480b-08a9-4b23-891a-df3febf00ead.png)

it is not possible to reach a configuration in which the thumb and the index superimpose one each other (please notice that in the above picture the thumb opposition is already at its maximum of approximately ~62 degrees. The same applies for the index adduction/abuction that is at 10 degrees).

On the other hand, in the real hand it is possible to reach this configuration, as I tried to do it today.

**Comment by traversaro** [comment]
fyi @pattacini @fiorisi

**Comment by pattacini** [comment]
Thanks @gabrielecaddeo for reporting 👍🏻 

@ale-git is busy these days with the development of a FW release to address an important upcoming demo.
We might have some time to look into it starting with our next sprint (Mon 20).

**Comment by traversaro** [comment]
In the meanwhile, some tips for @gabrielecaddeo so that you can continue to debug on your own and prepare useful information for domain experts.

First of all, which version (tagged version or git commit checkout if you are not in a released version) of `icub-models` are you using? Which version of YARP? Which version of Gazebo? Which version of gazebo-yarp-plugins?

> it is not possible to reach a configuration in which the thumb and the index superimpose one each other (please notice that in the above picture the thumb opposition is already at its maximum of approximately ~62 degrees. The same applies for the index adduction/abuction that is at 10 degrees).

Can you report this information using the precise identifier of joint names, i.e. the one that you find in the URDF? Using ambigous names may lead to confusion that make debugging harder.

> On the other hand, in the real hand it is possible to reach this configuration, as I tried to do it today.

If you are able to reproduce this configuration with the real hand, can you report in the issue the exact configuration of the hand (i.e. in a table with joint/axis names and their values?). After that, you can try to reproduce the same configuration in simulation, for example using `yarpmotorgui`. If you try that, I guess that there are two possible outcomes:
* You are able to have in the simulated robot the same configuration, but in the real hand the fingertip do not touch. This may indicate that there is something wrong (i.e. not matching the real hand) **in the simulated URDF kinematic model** or in the **coupling laws** added in https://github.com/robotology/gazebo-yarp-plugins/pull/469 .
* You are **not** able to reproduce the same configuration in simulation. This may indicate that something is wrong in the joint/axis limits.

**Comment by gabrielecaddeo** [comment]
> First of all, which version (tagged version or git commit checkout if you are not in a released version) of `icub-models` are you using? Which version of YARP? Which version of Gazebo? Which version of gazebo-yarp-plugins?

I am using `YARP` 3.4.5+6-20210610.3+gitfdc109fa6, `Gazebo 11.8.1`, the last commit of `icub-models` (devel branch, b9d4d49fe4571d5823cb1b59766bcdef0326945c), `gazebo-yarp-plugins` 0d18d2ed4e20c6cfb751e976171781df0deb9acd v3.6.1.

> Can you report this information using the precise identifier of joint names, i.e. the one that you find in the URDF? Using ambigous names may lead to confusion that make debugging harder.

In my opinion, the problem is with the `l_thumb_oppose joint` (JOINT 0) that reaches just 62 degrees. The other joint I was talking about is the `l_thumb` (JOINT 2)


> If you are able to reproduce this configuration with the real hand, can you report in the issue the exact configuration of the hand (i.e. in a table with joint/axis names and their values?)

I am not sure I can control the real hand at the moment, because it is under test on the first floor. I went there and I asked if I could move the fingers with my hand to see the limits of the real joints. I can try to go there and  ask if i can move it with the software.

**Comment by traversaro** [comment]
Thanks @gabrielecaddeo !

> > If you are able to reproduce this configuration with the real hand, can you report in the issue the exact configuration of the hand (i.e. in a table with joint/axis names and their values?)
> 
> I am not sure I can control the real hand at the moment, because it is under test on the first floor. I went there and I asked if I could move the fingers with my hand to see the limits of the real joints. I can try to go there and ask if i can move it with the software.

Sorry, I misunderstood then. I think at some point there was a working prototype, probably you can ask, otherwise we can wait for @ale-git input.

**Comment by traversaro** [comment]
To do some tests, you can try to increase the software and hardware limits in:
Software Limits: https://github.com/robotology/icub-models/blob/v1.21.1/iCub/conf_icub3/gazebo_icub_left_hand_thumb.ini#L68

The hardware limits should be defined in https://github.com/robotology/icub-models/blob/v1.21.1/iCub/robots/left_hand_mk3/model.urdf#L261, but I am bit confused as there I can only find the `l_hand_thumb_proximal_joint`, `l_hand_thumb_distal_joint` and `l_hand_thumb_rotation_joint` joints, no reference to `l_thumb` and `l_thumb_oppose` joints.

**Comment by traversaro** [comment]
I think I got it. The actual software limits (for the coupled controlled axis, that have indeed the correct `l_thumb`, `l_thumb_oppose` names) are defined in https://github.com/robotology/icub-models/blob/c73aa1d7e42e571c0b5b9f12043a07f9a1377e3f/iCub/conf_left_hand_mk3/left_hand_phys.ini#L24 , so feel free to try to change them or the hardware limits.

**Comment by ale-git** [comment]
Hi @gabrielecaddeo,
the Mk3 hand is designed with an additional DOF

![image](https://user-images.githubusercontent.com/4729270/133101233-a83a682d-4bf7-4c5c-b49d-4511416ba806.png)

so that the pinch grasp is achievable. In your screenshot the thumb (second joint in yarpmotorgui) is not rotated, i.e. it seems in 0 degrees position, while it can reach -70 degrees.

**Comment by gabrielecaddeo** [comment]
> so that the pinch grasp is achievable. In your screenshot the thumb (second joint in yarpmotorgui) is not rotated, i.e. it seems in 0 degrees position, while it can reach -70 degrees.  
Hi @ale-git .
Since it is a negative rotation, it is even worst for the grasp, because the thumb would be orthogonal to the index.
I attach a pic here
![WhatsApp Image 2021-09-13 at 16 58 44](https://user-images.githubusercontent.com/49904924/133107658-9979026a-e39e-4ecd-981f-84bae2148fac.jpeg)

**Comment by ale-git** [comment]
Well, also in human hand thumb and index aren't perfectly opposed but kinda lateral in pinch grasp. Please consider that you don't have to go to -70, but you have to rotate just the amount you need. Btw, can you post a picture of the real hand performing the grasp you desire? Maybe there is an offset in the rotation limits between the real hand and the model.

**Comment by gabrielecaddeo** [comment]
I did not post the picture of the real hand since this is public, but I will now, sorry.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/49904924/133109848-b8153836-14b7-440c-82c2-99f73b7bf748.png)

Clearly it is not perfectly "parallel" but it is very close to the desidered configuration.

**Comment by ale-git** [comment]
Maybe the thumb opposition limit is changed @marcellosavoldi ?

**Comment by marcellosavoldi** [comment]
Hi guys... sorry for late.
The limit range is not changed .
I confirm that the opposition of the index and thumb is not parallel, but the fingertip of the thumb touches the index when it is slightly inclined.
![image](https://user-images.githubusercontent.com/53296021/133976686-23b9c5f8-19af-48c9-bce6-dc84e35a4260.png)
![image](https://user-images.githubusercontent.com/53296021/133976861-de0a346a-8429-4c87-96c1-f9c48dbb23e9.png)

metacarpus 0-80°
thumb rotation 0-70° ( to be honest , I dont remember the zero position... could be +35,-35° ... or 0,-70? )

**Comment by ale-git** [comment]
The thumb metacarpus range in the configuration file is smaller:

![image](https://user-images.githubusercontent.com/4729270/133977755-5b72966a-4839-4572-98e5-089be096c3c1.png)

We must increase it to 80 degrees, and the difference between the URDF and physical model should vanish.

**Comment by traversaro** [comment]
I guess this value should be updated in two places:
* https://github.com/robotology/icub-models-generator/blob/v1.21.1/simmechanics/data/components/left_hand_mk3/simmechanics2urdf_joints_configfile.csv#L2
* https://github.com/robotology/icub-models-generator/blob/v1.21.1/simmechanics/data/components/left_hand_mk3/conf/left_hand_phys.ini#L25

Anyone interested is welcome to submit a PR, thanks!

**Comment by pattacini** [comment]
Fixed in https://github.com/robotology/icub-models-generator/pull/211.

**Comment by traversaro** [comment]
Thanks @mfussi66 !
