### ISSUE TITLE
`velocityControlImplementationType` missing parameter for iCubGazeboV3

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#106]
This parameter is required after the gazebo yarp plugin v4.0.0 release

**Comment by mebbaid** [comment]
any updates on this issue ?

**Comment by GiulioRomualdi** [comment]
This should fix the issue
 https://github.com/robotology/icub-models-generator/pull/212

Could you try with the devel branch?

**Comment by mebbaid** [comment]
@traversaro this maybe the issue that the Jonathan from Australia was having  (he mentioned this during the ergocub update meeting). Couldn't tag him because i didn't find him on this site.

**Comment by GiulioRomualdi** [comment]
Given

**Comment by lrapetti** [comment]
> @traversaro this maybe the issue that the Jonathan from Australia was having (he mentioned this during the ergocub update meeting). Couldn't tag him because i didn't find him on this site.

@Woolfrey

**Comment by traversaro** [comment]
Thanks a lot @mebbaid, I think indeed that it is! https://github.com/robotology/icub-models/commit/6239efecaf2d19368d14ad5a322ec0afc767c8a8 (and the related PR https://github.com/robotology/icub-models-generator/pull/212) fixed it in devel, but probably @Woolfrey downloaded either master or released version of icub-models. Let's release a new version of icub-models so users can get a working iCub3 models without a lot of hassle.

**Comment by traversaro** [comment]
Hopefully we can do a 1.22 release (see https://github.com/robotology/icub-models/pull/109) to avoid confusion in all users.

**Comment by traversaro** [comment]
> 
> 
> Hopefully we can do a 1.22 release (see #109) to avoid confusion in all users.

Done: https://github.com/robotology/icub-models/releases/tag/v1.22.0 .

**Comment by traversaro** [comment]
> 
> 
> > Hopefully we can do a 1.22 release (see #109) to avoid confusion in all users.
> 
> Done: https://github.com/robotology/icub-models/releases/tag/v1.22.0 .

I also updated the `LatestReleases` file in the robotology-superbuild: https://github.com/robotology/robotology-superbuild/pull/920 . So the next conda package generation will get the updated icub-models, let me know if there is anything else that we could do to make sure that this issue is fixed without the need for the user to manually switch branches or do stuff like that. @mebbaid @Woolfrey

**Comment by mebbaid** [comment]
@traversaro it seems that this fixes the initial issue and the `iCubGazeboV3` starts correctly.

**Comment by Woolfrey** [comment]
I saw this; thanks!

Github notifications are being sent to my gmail instead of my iit email.
