### ISSUE TITLE
Run the iCub's Gaze controller on Gazebo 

### ISSUE THREAD

**Issue by robertorovella91** [robotology/icub-models#117]
So there is no possibility to run gaze controller on Gazebo? 

_Originally posted by @robertorovella91 in https://github.com/robotology/icub-gazebo/issues/62#issuecomment-456014072_

**Comment by xEnVrE** [comment]
It has been fixed, the Gaze controller can now be used in Gazebo with the manually generated model `iCubGazeboV2_5_visuomanip`.

Here is a complete example where the Gaze is used: https://github.com/robotology/icub-gazebo-grasping-sandbox

**Comment by traversaro** [comment]
> Not sure about the old models in `icub-gazebo`.

No problems, those have been deprecated since some time, thanks!
