### ISSUE TITLE
Move in robotology?

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-models#14]
I think that the repo has been used for relativly a long time, and so it is time to move it to robotology. 
Opinions on that? @nunoguedelha @diegoferigo @gabrielenava @S-Dafarra ?

**Comment by traversaro** [comment]
@fiorisi do you agree?

**Comment by diegoferigo** [comment]
:+1:

**Comment by traversaro** [comment]
Done. GitHub's support for redirecting is quite good, but it would idea if we could cleanup any leftover of the robotology-playground link.
