### ISSUE TITLE
Possible typo in iCubGazeboV2_5_visuomanip urdf

### ISSUE THREAD

**Issue by fedeceola** [robotology/icub-models#140]
I noticed that in the iCubGazeboV2_5_visuomanip urdf the mesh for collision computation for the link l_hand_little_1 is full_LeftLittle1.dae https://github.com/robotology/icub-models/blob/4c911ad591f9362d100d89cee1e282e7fe91384c/iCub_manual/robots/iCubGazeboV2_5_visuomanip/model.urdf#L2356 while for the link r_hand_little_1 is col_RightLittle1.dae. https://github.com/robotology/icub-models/blob/4c911ad591f9362d100d89cee1e282e7fe91384c/iCub_manual/robots/iCubGazeboV2_5_visuomanip/model.urdf#L1441 Is it intended?

**Comment by pattacini** [comment]
cc @xEnVrE

**Comment by xEnVrE** [comment]
It really seems a typo, I can handle it.
