### ISSUE TITLE
iCubGazeboV3 - joint limits of shoulder pitch not aligned with limits of iCubGenova09 

### ISSUE THREAD

**Issue by isorrentino** [robotology/icub-models#157]
As you can see from this picture, the joint limits of the shoulder pitch joints of iCubGazeboV3 (all the models available for simulation) are not aligned with the ones of iCubGenova09.

![Screenshot from 2022-05-25 15-37-17](https://user-images.githubusercontent.com/43743081/170275545-7a6a0a01-b39a-40a1-b867-268ab0ccb7a4.png)

These are the old limits, before the hardware modification, and maybe the iCubGazeboV3 models have not been updated.

**Comment by pattacini** [comment]
Hi @isorrentino 

We are about to release in the upcoming days an update of the iCub 3 URDF to fix some weight discrepancies.
We can take care of this as well.

**Comment by Mick3Lozzo** [comment]
@isorrentino this will soon be fixed by @mfussi66 
cc @pattacini

**Comment by pattacini** [comment]
@mfussi66 reported that:

>The model just pushed by the CI in `icub-models/devel` works as expected:
![image](https://user-images.githubusercontent.com/38140169/177148722-c7c2d648-b442-4505-982b-0f766154ffcd.png)
>
>And with the `/left_leg/analog:o` port working correctly to read the FT sensor.

The fix landed via https://github.com/robotology/icub-models/commit/8ad63f19211c3e8802ebb9f8593283713031dca9.

**Comment by pattacini** [comment]
Closing, feel free to open it up again if deemed required.
