### ISSUE TITLE
Release new version of icub-models and whole-body-estimators

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-models#164]
Apparently there is a strict relation between the recent changes in the iCub3 model (https://github.com/robotology/icub-models-generator/pull/223, https://github.com/robotology/icub-models/commit/8ad63f19211c3e8802ebb9f8593283713031dca9) and similar changes in the whole-body-estimators configuration files (see https://github.com/robotology/whole-body-estimators/pull/154).

To avoid confusion, it would be a good idea to make a new release of icub-models and whole-body-estimators, so that the latest version of both will be compatible with each other.

cc @RiccardoGrieco @RiccardoZuppetti @isorrentino @GiulioRomualdi @S-Dafarra

**Comment by traversaro** [comment]
Indeed, @RiccardoZuppetti confirmed that only `devel` of `icub-models` is compatible with `master` of `whole-body-estimators` . While doing a release of `whole-body-estimators` requires coordination, something that we can already do to reduce friction for users is to `merge` devel in master for `icub-models`, to ensure that `master` of icub-models is compatible with `master` of `whole-body-estimators`.

**Comment by traversaro** [comment]
I forgot to mention @HosameldinMohamed .

**Comment by HosameldinMohamed** [comment]
Released [v0.8.0](https://github.com/robotology/whole-body-estimators/releases/tag/v0.8.0) for `whole-body-estimators`. to include https://github.com/robotology/whole-body-estimators/pull/154.

**Comment by traversaro** [comment]
icub-models release: https://github.com/robotology/icub-models/releases/tag/v1.25.0 .
