### ISSUE TITLE
Create iCubGazeboV3_visuomanip

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-models#169]
For simulations related to teleoperation, it would be useful to have an iCubGazeboV3 model with moving eyes, cameras and moving hands. However, in the short term it would be difficult to obtain this information directly from the CAD, so probably we need to create this model by taking the hands and he head from the `[iCubGazeboV2_5_visuomanip](https://github.com/robotology/icub-models/tree/master/iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip)`, and adding them to the existing `iCubGazeboV3` model. 

Related issues:
* https://github.com/robotology/icub-models/pull/42
* https://github.com/robotology/icub-models-generator/issues/37
* https://github.com/robotology/icub-models-generator/issues/29

cc @S-Dafarra

**Comment by mebbaid** [comment]
On it, will look at the provided link, and maybe ask for help if needed.

**Comment by Woolfrey** [comment]
Hi @traversaro, @mebbaid, I tried using this model and there's a bit of a problem with the hands!

![image](https://user-images.githubusercontent.com/62581255/195627715-25c93e37-be1c-42ce-85ca-410acb47579c.png)

Gazebo also seems to freeze a lot when I load this model, which may or may not be related to the detached hands:

![image](https://user-images.githubusercontent.com/62581255/195628131-b475f4b0-e442-4486-bd13-cabfbd5358fe.png)

**Comment by mebbaid** [comment]
@Woolfrey : try to pull and compile against this fork https://github.com/mebbaid/icub-models instead of the usual `icub-models` master and see if this issue is resolved.

**Comment by traversaro** [comment]
@mebbaid if that works, can you propagate it to https://github.com/robotology/icub-models/ ? Thanks!

**Comment by mebbaid** [comment]
certo @traversaro . It seems to fix the issue on my side and Ehsan's side. Waiting fro @Woolfrey to confirm that the fix works for him as well before opening a PR.

**Comment by Woolfrey** [comment]
@mebbaid , yes that seemed to work:

![image](https://user-images.githubusercontent.com/62581255/195797270-8dfd77c5-06a3-4d6b-9b7d-fff92a097ef2.png)

**Comment by Woolfrey** [comment]
@mebbaid @traversaro, I got the model to load and it seems to be working with my controller, however it seems the right hand is producing some sort of force field when I push a box:

![Magic](https://user-images.githubusercontent.com/62581255/196165676-e9d997bf-f0aa-4178-93b7-8d9d74bd3496.gif)

**Comment by mebbaid** [comment]
This suggests to me that there is some issue with the `collision` parameters in the urdf for the right hand only. I will check it, and if that is the case I will push the fix to the fork

**Comment by traversaro** [comment]
Note that in Gazebo you can enable the visualization of collision meshes to debug this sort of behaviour.

**Comment by mebbaid** [comment]
Indeed it was the `collision` group of the `r_hand` link, as the following pic shows. 

![image](https://user-images.githubusercontent.com/36491318/196182530-f16ab71c-6b96-4c28-bcd4-65a3da76ea02.png)


I have pushed a commit https://github.com/mebbaid/icub-models/commit/0f25a16835a562c5091a2e3eb38dd8271e0aedbd in the fork with a fix as in the pic below. Let me know @Woolfrey if it works for you and that the intuition was correct.

![image](https://user-images.githubusercontent.com/36491318/196181410-da2267e7-bef7-47eb-8588-a026bb465695.png)

**Comment by Woolfrey** [comment]
@mebbaid, it seems to have worked!

![image](https://user-images.githubusercontent.com/62581255/196470392-20bef19a-76b1-4794-8071-0cacc8f6e4ac.png)
