### ISSUE TITLE
Old configuration files - presumably not used

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-models#185]
While I was working on https://github.com/robotology/icub-models/issues/171#issuecomment-1396944172, I noticed that there are several files inside https://github.com/robotology/icub-models/tree/devel/iCub/conf, where ideally only automatically generated file should stay, that are not updated by the GitHub action.

I am wondering whether these are really used by some of the automatically generated models or not. As an example, I think that automatically generated models are using the file:
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_left_arm_no_hand_for_no_hand_model.ini

while the repository still hosts:
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_left_arm_no_hand.ini
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_left_arm_no_forearm.ini

having their last commit 3 years ago and still using the `controlboardwrapper2`.

Other files are probably not required anymore:
- all the files having names like `gazebo_icub_{left, right}_hand_<finger_name>.ini` as the manual models have their equivalent counterparts inside https://github.com/robotology/icub-models/tree/devel/iCub_manual
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_head.ini
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_left_hand_mais.ini
- https://github.com/robotology/icub-models/blob/devel/iCub/conf/gazebo_icub_right_hand_mais.ini

Should we think of removing these files in order to tidy up the configuration folder?

**Comment by traversaro** [comment]
Thanks for opening this issue! 

To avoid having this problem again, we should delete everytime all the files in the directory of automatically generated files.

**Comment by traversaro** [comment]
Ok, I started tackling this with:
* https://github.com/robotology/icub-models/pull/186
* https://github.com/robotology/icub-models-generator/pull/236

Once this are done, we need to actually delete the files.
