### ISSUE TITLE
ICub default posture

### ISSUE THREAD

**Issue by cmastalli** [robotology/icub-models#21]
Hi guys,

I was looking for the joint values for a default posture. I meant the posture that the robots has in when it's standing statically.

Grazie mille,
Carlos

**Comment by traversaro** [comment]
Hi @cmastalli ! 
It depends on the specific model of iCub, but for the `iCubGazeboV2_5` stored in this repo the position that we typically use for balancing experiments `TwoFeetStanding` position stored in https://github.com/robotology/codyco-modules/blob/master/src/modules/torqueBalancing/app/robots/iCubGazeboV2_5/homePoseBalancing.ini#L20 or the `YogaPP` position stored in the same file: https://github.com/robotology/codyco-modules/blob/master/src/modules/torqueBalancing/app/robots/iCubGazeboV2_5/homePoseBalancing.ini#L6 .

@gabrielenava can add more information if necessary, and feel free to ask more clarifications.

**Comment by cmastalli** [comment]
@traversaro grazie mille!
