### ISSUE TITLE
Name of joint "*_hand_finger" differ between simulation and the real robot iCubGazeboV2_5_visuomanip 

### ISSUE THREAD

**Issue by PasMarra** [robotology/icub-models#210]
While using the model `iCubGazeboV2_5_visuomanip`  in Gazebo I noticed that the name of the joint `*_hand_fingers` is different from that of real robots. For example, the configuration file for Gazebo is the following:
https://github.com/robotology/icub-models/blob/9f5e04bbb0c119bb045db88ee333ac55d616cd92/iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_left_hand_finger.ini#L15

while the name of the same joint, taken from the [documentation](https://icub-tech-iit.github.io/documentation/icub_kinematics/icub-joints/icub-joints/#left-arm) of the real robot is as follows: 

![image](https://github.com/robotology/icub-models/assets/143645988/5e2f58c7-8022-4e92-adcf-d9f7504b31d7)

i.e. without the final s. Should I open a PR to fix that?

**Comment by traversaro** [comment]
Sorry, I forgot to reply. Yes, this is a bug. The correct one (by definition) is the one in the docs, if the model or the real robot does not match, they should be fixed. Please provide a PR, thanks!
