### ISSUE TITLE
Simulated finger hall effect sensors for iCubGazeboV2_5_visuomanip have wrong port names

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-models#214]
As per the title, the ports that the system open are as follows

```
registration name /iCub/left_hand/analog:o ip 172.17.0.1 port 10003 type tcp
registration name /iCub/left_hand/analog:o/rpc:i ip 172.17.0.1 port 10002 type tcp
registration name /iCub/right_hand/analog:o ip 172.17.0.1 port 10005 type tcp
registration name /iCub/right_hand/analog:o/rpc:i ip 172.17.0.1 port 10004 type tcp
```

while they should begin with `icubSim`.

The problem seems to be that the following include:

https://github.com/robotology/icub-models/blob/2eb7ff8ffd212c639249cf00a2bc9a7dd9f0cd2c/iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/gazebo_icub_right_hand_mais.ini#L1

is failing as the `iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip` folder does not contain the `gazebo_icub_robotname.ini`.

Can I open a PR to add that file?

Or, given that file is basically unused as, for the rest, we provide the portprefix via the `yarprobotinterface` plugin, e.g.:

https://github.com/robotology/icub-models/blob/2eb7ff8ffd212c639249cf00a2bc9a7dd9f0cd2c/iCub_manual/conf_manual/iCubGazeboV2_5_visuomanip/icub.xml#L4

should I open a PR to hardcode `icubSim` within the `*_mais.ini` files?

Thank you

cc @traversaro

**Comment by traversaro** [comment]
> should I open a PR to hardcode `icubSim` within the `*_mais.ini` files?

Yes, I think that is the easiest solution.
