### ISSUE TITLE
Clarification on the FT frames in the FT CAD model

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-models#22]
Looking at the CAD model of the FT sensors, more specifically, `ic_007_a_001.asm`, for the FT sensor with M3 skrews, I noted that the `SCSYS_FT45` frame, which should be the **sensor frame** of the FT sensor, is reversed w.r.t. the `sketch` that represents the positive **x** and **y** axis of the sensor's frame. See the pictures below:

![FT_frames](https://user-images.githubusercontent.com/12396934/58089526-45b87100-7bc5-11e9-87ac-dca08ba26283.PNG)
![FT_sketch](https://user-images.githubusercontent.com/12396934/58089585-74364c00-7bc5-11e9-8207-00bde28e5a1d.PNG)

@fiorisi am I missing something here? Which frame should I follow when mounting the FT?

**Comment by traversaro** [comment]
For reference, the FT sensor frame is documented in http://wiki.icub.org/wiki/FT_sensor .

**Comment by gabrielenava** [comment]
Mmh, comparing the wiki and the CAD it seems that the `sketch` is  not the sensor frame, as in the wiki the **x** axis is pointing in the direction opposite to the one where there is the **hole for the cable**, but this is not the case in the CAD model:


![FT_frames_wiki](https://user-images.githubusercontent.com/12396934/58095144-9aaeb400-7bd2-11e9-8166-39a246d37caf.PNG)
![FT_sketch_comp](https://user-images.githubusercontent.com/12396934/58095145-9aaeb400-7bd2-11e9-9179-880c139f800b.PNG)

But the models are not the same, as the skrews pattern placement is different. I'll follow the wiki convention for now.

**Comment by traversaro** [comment]
As the `SCSYS_FT45` and the wiki definition are consistent, I would say that those sketch are misleading, but @fiorisi can probably provide more insight. 

A possible explanation of those strange directions in the sketch is that a tricky part of defining FT sensors measures is that defining the **coordinate frame** in which the force and torque are expressed is not sufficient, you also need to specify if the measured force is the one that the "top" of the sensor is exerting on the "bottom", or the one that the "bottom" is exerting on the "top". In SDF, this characteristic is called `measure_direction`. See https://bitbucket.org/osrf/gazebo/issues/940/force-torque-sensor-forcetorquesensorcc, https://github.com/robotology/gazebo-yarp-plugins/issues/73 and http://gazebosim.org/tutorials?tut=force_torque_sensor&cat=sensors for more info on this. 

An important thing to note is that as long as those two forces are expressed in the same frame, the only difference is in their sign by the Newton's third law ( https://en.wikipedia.org/wiki/Newton%27s_laws_of_motion#Newton%27s_third_law ). However it is extremely common, especially is someone is considering  only two components of the measure, to mistake a different `measure_direction` of the FT sensor for the fact that the measure is expressed in a different reference frame, that is actually only possible if you consider left handed reference frames.

**Comment by fiorisi** [comment]
Thanks @gabrielenava for checking the frame in this model.
Please note that anyhow the assembly `ic_007_a_001.asm` refers to the FT model `Mk3`. 
In your design please use the `Mk4` which corresponds to the assembly `ic_008_a_001.asm`.
In this assembly the frame was corrected when we used the sensor in the [AnDy sandals CAD model](https://github.com/dic-iit/element_ftSk_Shoes/issues/71).

![image](https://user-images.githubusercontent.com/8970230/58170083-c72a0500-7c92-11e9-87a1-05ab6578f276.png)

cc @miggia

**Comment by gabrielenava** [comment]
Thanks @fiorisi, the `ic_008_a_001.asm` is coherent with the wiki and sketch and sensor frame have the same orientation. I changed the FT sensor I amusing in the CAD. Closing the issue.
