### ISSUE TITLE
iCub >= V2.6: investigate orientation of the head imu frame 

### ISSUE THREAD

**Issue by martinaxgloria** [robotology/icub-models#231]
During the test on the IMU mountend on icub-head, @Nicogene and I found out that `head_imu_0`, which is the imu frame in the urdf, was not properly oriented. After the additional transformation for iCubs > v2_5 that was added here:

- https://github.com/robotology/simmechanics-to-urdf/pull/60

we saw that something was already wrong with the orientation data retrieved from the sensor. This is the result of the test on iCubGenova11:

[test-icub.webm](https://github.com/robotology/icub-models/assets/114698424/a2078f6a-75bb-4763-8f12-d25acfa176c2)

We tried to understand if the imu frame is oriented in the same way in both iCub > v2_5 and ergoCub models and so it is, as reported in the figures below.

- `ergoCubGazeboV1`:

![head_imu_0_ergoCubGazeboV1](https://github.com/robotology/icub-models/assets/114698424/e36e2405-76bd-4e46-a446-69910b4c273b)

- `iCubGazeboV2_7`:

![Screenshot from 2024-01-29 10-56-45](https://github.com/robotology/icub-models/assets/114698424/fc55b07b-5e85-4c2e-8a16-f6025b808b53)

However, running the same test for the imu on the head on ergoCub1.1, instead, the result reported below shows that the expected and measured orientation traces follow each other, as expected:

[test_imu_ergocub.webm](https://github.com/robotology/icub-models/assets/114698424/3e3d5e5d-0d01-473d-8a32-ed08eb555924)

cc @traversaro

**Comment by traversaro** [comment]
Could this be something at the firwmare level? The version of the firmware in the related boards of iCubGenova11 and ergoCubSN001 is the same?

**Comment by martinaxgloria** [comment]
> Could this be something at the firwmare level? The version of the firmware in the related boards of iCubGenova11 and ergoCubSN001 is the same? 

Both the iCubGenova11 and ergoCub1.1 rfe firmware version is v1.4.0.

**Comment by traversaro** [comment]
Did you double checked if the board are mounted in the same way in the two heads?

**Comment by Nicogene** [comment]
> Did you double checked if the board are mounted in the same way in the two heads?

Yes they seems mounted differently on the two robots

### ergoCub
![immagine](https://github.com/robotology/icub-models/assets/19152494/19d24c92-5695-4050-bae9-537e63123734)

### iCub
![immagine](https://github.com/robotology/icub-models/assets/19152494/5843be02-b0e6-44ee-a0c7-0dab21ea30f2)

I don't know why we didn't mount it in the same way, maybe @Mick3Lozzo knows it.

We need to re-check the csys of the imu in the iCub simulation model also at iKin level

cc @traversaro @fiorisi @martinaxgloria @pattacini

**Comment by traversaro** [comment]
Then I guess one of the two models is wrong?

**Comment by Nicogene** [comment]
On ergoCub the cad of real robot and simulation model seems consistent

![immagine](https://github.com/robotology/icub-models/assets/19152494/7802fd81-b708-4613-8fe2-8c4df071408b)


![immagine](https://github.com/robotology/icub-models/assets/19152494/1c91881d-889b-4fca-b72b-e7fa97adda20)


so it is iCub the faulty one

**Comment by martinaxgloria** [comment]
I confirm that the two rfe are differently oriented (I was checking with the help of @AntonioConsilvio). I highlighted the two imu frame on the cad and I obtained this:

- ergoCub

![immagine (1)](https://github.com/robotology/icub-models/assets/114698424/7f636497-38e4-4257-8b4a-8af3ea15d5b6)

- iCub

![immagine](https://github.com/robotology/icub-models/assets/114698424/b6540dd5-e14c-42e1-9da7-781b16224b46)

Making a comparison with what we saw on rviz, it seems that the robot that has a correspondence between the urdf and the cad is ergoCub, right?

cc @Nicogene @traversaro

**Comment by Nicogene** [comment]
Alongside @lawproto, we recomputed the transformation between the frame of the "old" mtx to the bno055 of the rfe and here is the result:

**SCSYS_HEAD_MTX_IMU -> BN0055_M-FRAME**
```
0.0000000000	1.00000	0.0000000000	6.65401
1.00000	0.0000000000	0.0000000000	4.00169
0.0000000000	0.0000000000	-1.00000	59.2493

```

Looking at this @traversaro comment
- https://github.com/robotology/icub-main/issues/570#issuecomment-520341954

The only difference is in the traslation, probably in the past we took the wrong starting frame, but the rotations are the same.

Maybe @traversaro we used the wrong euler convention while transforming the rotation matrix to euler angles? I remember we looked which was the correct one to be used, I think we adopted the XYZ

**Comment by Nicogene** [comment]
In the sdf specification it is stated:

![immagine](https://github.com/robotology/icub-models/assets/19152494/4b65a0d7-1cc3-4009-85c8-2c969a197ce7)


This means that we need transform to euler angles using the sequence ZYX?

**Comment by traversaro** [comment]
To transform from Rotation matrix to URDF's rpy I would just use the related iDynTree::Rotation function, it has been extensively tested as part of URDF Import/Export functionality of iDynTree, example code:

~~~python
import idytree.bindings as idt
import numpy as np

angle_radians = np.radians(30)

# Create rotation matrix
rotation_matrix_x = np.array([
    [1, 0, 0],
    [0, np.cos(angle_radians), -np.sin(angle_radians)],
    [0, np.sin(angle_radians), np.cos(angle_radians)]
])

rot_idyn = idt.Rotation(rotation_matrix_x).asRPY().toNumPy()
~~~

**Comment by martinaxgloria** [comment]
Hi @traversaro. I followed your suggestion and, starting from the rotation matrix retrieved with CREO (the one posted by @Nicogene a few comments above), I obtained the correspondent RPY orientation. 

```py
>>> import idyntree.bindings as idt
>>> import numpy as np
>>> rotMat = np.array([
... [0, 1, 0],
... [1, 0, 0],
... [0, 0, -1]
... ])
>>> rot_eul = idt.Rotation(rotMat).asRPY().toNumPy()
>>> rot_eul
array([ 3.14159265, -0.        ,  1.57079633])
```

I regenerated the urdf model by inserting this orientation within the CMakeLists.txt and I visualized the transformation on rviz2, which now is the same of the one on the CAD model:

![image](https://github.com/robotology/icub-models/assets/114698424/0ff2449a-21e9-4514-bb27-a51a8c4d560a)

I'm unable to visualize the meshes on rviz, maybe a problem in the model generation, but I checked the orientation with all the TFs enabled (the one on the top is the `head_imu_0` frame:

![image](https://github.com/robotology/icub-models/assets/114698424/b0fc7e55-ee92-4464-9a75-01f61ed99994)

**Comment by martinaxgloria** [comment]
I tried to do the same as iDynTree but with Matlab to obtain the same Euler angles values and I found out that the used convention is the `YXZ`:

```matlab
>> R = [0 1 0; 1 0 0; 0 0 -1]

R =

     0     1     0
     1     0     0
     0     0    -1

>> R_eul = rotm2eul(R, "YXZ")

R_eul =

    3.1416         0    1.5708
```

maybe, this information could be useful.

cc @Nicogene @traversaro @pattacini

**Comment by traversaro** [comment]
Just to be sure, I would try this with a couple more rotations to be sure that the two methods are equivalent, otherwise we may be just lucky/unlucky that the two methods match in that specific case but not in general.

**Comment by martinaxgloria** [comment]
> Just to be sure, I would try this with a couple more rotations to be sure that the two methods are equivalent, otherwise we may be just lucky/unlucky that the two methods match in that specific case but not in general.

You're right, I've tried with some rotation matrices and they didn't match in all the examined cases. So, we could keep on with the iDynTree::Rotation method to transform the rotation matrix into rpy angles.

cc @Nicogene @traversaro

**Comment by martinaxgloria** [comment]
Today, @Nicogene and I tested the new head imu frame after https://github.com/robotology/icub-models-generator/pull/258 on iCubGenova11 using the IMU test. This was the result:

https://github.com/robotology/icub-models/assets/114698424/eff54553-04d0-494f-addc-a0b76483cfc9

Now the test passes! I think we can close this issue.

cc @traversaro @pattacini

**Comment by traversaro** [comment]
> Now the test passes! I think we can close this issue.

Great! I want to do a quick release of icub-models to release this (fundamental) fix, then I will close it, thanks again!

**Comment by traversaro** [comment]
> > Now the test passes! I think we can close this issue.
> 
> Great! I want to do a quick release of icub-models to release this (fundamental) fix, then I will close it, thanks again!

Fixed in https://github.com/robotology/icub-models/releases/tag/v2.5.0, thanks to @martinaxgloria and @Nicogene !
