### ISSUE TITLE
Add IMU frame of ft-stain2 in the models.

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-models#24]
Since now we have the IMU in the ft sensor we should add it.

cc @fiorisi @traversaro @nunoguedelha @prashanthr05

**Comment by fiorisi** [comment]
@fjandrad there was an issue to add the frames in the model and a dedicated PR. I have to check why the build is failing.
Related PR: https://github.com/robotology/icub-model-generator/pull/111
Related issue: https://github.com/robotology/icub-model-generator/issues/91

**Comment by fiorisi** [comment]
cc @lia2790

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/icub-model-generator/pull/122 , thanks to everyone that contributed.
