### ISSUE TITLE
[Q/A] Query regarding Gazebo foot collision elements 

### ISSUE THREAD

**Issue by prashanthr05** [robotology/icub-models#38]
Few SDF collision elements [here](https://github.com/robotology/icub-models/blob/371cc30d27f079d4407e209395ff6a691293abc1/iCub/robots/iCubGazeboV2_5/model.urdf#L2237), for the foot seems to be outside the parent tag `collision`.

``` xml
  <maxContacts>4</maxContacts>
  <kp>18000000</kp>
  <kd>100</kd>
  <maxVel>100</maxVel>
  <minDepth>0.0001</minDepth>
  <mu1>1</mu1>
  <mu2>1</mu2>
  <fdir1>0 0 0</fdir1>
```

Also, http://sdformat.org/spec?elem=collision&ver=1.6 specifies `max_contacts` tag. Moreover, the parameters `kp`, `kd`, `mu1`, etc fall as children of `friction`->`physics_engine` (where in this example, `physics_engine` is a place-holder. eg, physics_engine `ode`) tags all under `surface` element.

There seems to be a mismatch between the SDF format and the gazebo reference tags written in the robot URDF file. Is this because we use the SDF tags within a URDF format?

**Comment by prashanthr05** [comment]
cc @nunoguedelha @traversaro @GiulioRomualdi

**Comment by GiulioRomualdi** [comment]
I think that also @diegoferigo may know the answer

**Comment by diegoferigo** [comment]
Here is the answer: http://gazebosim.org/tutorials?tut=ros_urdf#%3Cgazebo%3EElementsForLinks

**Comment by prashanthr05** [comment]
Great, Thanks!
