### ISSUE TITLE
[iCubGazeboV3] Ankles roll goes in HF for a given value of ankle pitch

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#60]
If the ankle pitch of the left foot is greater than 13deg the ankle roll goes in HF

![icub3-right_ankle-hf](https://user-images.githubusercontent.com/16744101/97011500-0b37ce00-1547-11eb-8ad3-919b22b776c7.gif)

The same behavior happens also for the right foot.
![icub3-right_ankle](https://user-images.githubusercontent.com/16744101/97011152-9bc1de80-1546-11eb-960d-0559d51da98b.gif)

 Notice that the joint axis of the two ankles seems to be not coherent (associate issue  https://github.com/robotology/icub-models/issues/61)

@Nicogene  and @traversaro

**Comment by traversaro** [comment]
The HF in the simulated robot is raised whenever the requested torque is higher then 2000 Nm, see https://github.com/robotology/gazebo-yarp-plugins/blob/52491d69365a32ad930f2b858b9f3a43e7596510/plugins/controlboard/src/ControlBoardDriver.cpp#L69 and https://github.com/robotology/gazebo-yarp-plugins/blob/52491d69365a32ad930f2b858b9f3a43e7596510/plugins/controlboard/src/ControlBoardDriver.cpp#L568 . What is happened there at the first glance seems related to some numerical error that leads the simulated system to diverge once controlled, i.e. a problem similar to https://github.com/robotology/icub-models/issues/53 . Does the problem disappears if you increase some inertias of some links of the foot?

**Comment by GiulioRomualdi** [comment]
Hi @traversaro changing the `max_step_size` from `0,001` to `0.0001` fixes the problem

**Comment by Nicogene** [comment]
Probably we have to fake inertias also here

**Comment by Nicogene** [comment]
@GiulioRomualdi it should be fine now, can you double-check?
