### ISSUE TITLE
[iCubGazeboV3] right leg joints direction wrongly defined 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#61]
The direction of the right joint seems to be wrongly defined 

This is `r_hip_roll`
![icub3-right_leg](https://user-images.githubusercontent.com/16744101/97010319-84362600-1545-11eb-8ba2-ee7bd14a485c.gif)

This is for the `ankle pitch`
![icub3-right_ankle](https://user-images.githubusercontent.com/16744101/97010953-5f8e7e00-1546-11eb-90f3-ad86b24e3544.gif)

Notice the ankle roll goes in HF for a specific value of `ankle-pitch` for this problem please check https://github.com/robotology/icub-models/issues/60

@traversaro and @Nicogene 
Similar issue: #57

**Comment by GiulioRomualdi** [comment]
Regarding `r_hip_roll` I'm pretty sure it's a bug so I can open a PR in the generator. Following robotology/icub-model-generator#150.

 For the ankles, I don't know if it's wanted

**Comment by traversaro** [comment]
> For the ankles, I don't know if it's wanted

As we don't have any document with the iCub3 direction, I guess the gold reference is the real robot.

**Comment by GiulioRomualdi** [comment]
https://github.com/robotology/icub-model-generator/pull/153 and https://github.com/robotology/icub-model-generator/pull/151 fix the problems
