### ISSUE TITLE
[iCubGazeboV3] The direction of several axis joints does not match the real robot  

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#64]
I'm currently in front of the robot with @isorrentino and I checked the joints motion of iCubGazeboV3 with iCub3. 

The following joints axes are wrongly mounted in the `urdf`
- torso_roll
- l_ankle_pitch
- r_hip_yaw
- r_ankle_roll

I didn't check the head and arms
cc @DanielePucci @traversaro @S-Dafarra and @Nicogene

**Comment by traversaro** [comment]
Feel free to submit a PR to fix this. As I mentioned in another issue, we don't have any docs on the intended direction of icub 3 axis, so the robot is our definite reference.
