### ISSUE TITLE
[iCubGazeboV3] Change feet collision meshes to simplified geometry

### ISSUE THREAD

**Issue by prashanthr05** [robotology/icub-models#66]
I am trying to change the feet meshes to replace it with simplified geometry.

I got the bounding box for the feet from MeshLab as,
|l_foot_front| l_foot_rear | r_foot_front| r_foot_rear|
|:--:|:--:|:---:|:---:|
|![l_foot_front](https://user-images.githubusercontent.com/6506093/98228135-7a0a2380-1f58-11eb-9ab5-23fdac6bd82e.png)|![l_foot_rear](https://user-images.githubusercontent.com/6506093/98228157-81c9c800-1f58-11eb-95ea-3f0ddbdc52cd.png)|![r_foot_front_bb](https://user-images.githubusercontent.com/6506093/98228175-87271280-1f58-11eb-87e8-eafe158cfd62.png)|![r_foot_rear](https://user-images.githubusercontent.com/6506093/98228195-8c845d00-1f58-11eb-957e-bcf2af2085cb.png)|

They all have the same dimensions and are in mm (I believe!).

However, in the URDF there seems to be a `scale` option for the mesh that scales the mesh's axis-aligned-bounding-box, according to http://wiki.ros.org/urdf/XML/link.  There's no further explanation. 

``` xml
      <geometry>
        <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_l_foot_rear_prt.stl" scale="0.001 0.001 0.001"/>
      </geometry>
```

I believe the scale is simply a unit conversion from millimeters to meters.

So I made the changes only to the `collision` part of the feet as
``` xml
    <collision>
      <origin xyz="0.010700000000000012 -0.06475000000001183 0.9464469999999995" rpy="0 0 -1.5707963267948966"/>
<!--      
      <geometry>
        <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_l_foot_rear_prt.stl" scale="0.001 0.001 0.001"/>
      </geometry>
-->
      <geometry>
        <box size="0.1 0.117 0.010299988"/>
      </geometry>
    </collision>
```

But looks like, there's something I am missing here, which can be seen as soon as we load the model,

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6506093/98230826-e5092980-1f5b-11eb-8ce9-df33e0964b3f.gif)

Anyone's got advice/prior experience on this? 
cc @nunoguedelha @traversaro @S-Dafarra @GiulioRomualdi

**Comment by S-Dafarra** [comment]
I guess this is what is done on iCub2.5
https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L527-L532

**Comment by prashanthr05** [comment]
> Can you provide a link to your modifications?

I have it [here](https://github.com/prashanthr05/icub-models/commit/1d6d38f5955ed9a1c3410dade0a02edf28ceaeed) for the time being.

**Comment by prashanthr05** [comment]
Looks like the origin for the collision geometry was modified in https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L527-L532

**Comment by S-Dafarra** [comment]
Can you try to put the robot fixed in the air and visualize the collisions?

**Comment by traversaro** [comment]
> I hope this was not done by trial-and-error?

This is specified in https://github.com/robotology/icub-model-generator/blob/master/simmechanics/CMakeLists.txt#L97 that was added in https://github.com/robotology/icub-model-generator/pull/85 .

**Comment by traversaro** [comment]
To simplify the debug, I strong suggest to temporary disabled the visual meshes, so you would see just simplified mesh that you add. For the dimension of the box and the placement, I suggest to use as a reference the location of the `l_sole` frames, as I imagine was done for iCub 2.5 .

**Comment by prashanthr05** [comment]
> > I hope this was not done by trial-and-error?
> 
> This is specified in https://github.com/robotology/icub-model-generator/blob/master/simmechanics/CMakeLists.txt#L97 that was added in [robotology/icub-model-generator#85](https://github.com/robotology/icub-model-generator/pull/85) .

I was wondering about the choice and source of the values in 


https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L528

which is different from,

https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L519

but seems to be the same as,

https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L116

**Comment by traversaro** [comment]
> https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L528
>
> which is different from,
>
> https://github.com/robotology/icub-models/blob/05e4e60ed08937fd292e34dd81119a0e7d78c7f6/iCub/robots/iCubGazeboV2_5/model.urdf#L519

Why they should be similar? The origin of the box is placed in the center of the box (see http://wiki.ros.org/urdf/XML/link) while the origin of the visual mesh is arbitrary.

**Comment by prashanthr05** [comment]
> To simplify the debug, I strong suggest to temporary disabled the visual meshes, so you would see just simplified mesh that you add. For the dimension of the box and the placement, I suggest to use as a reference the location of the `l_sole` frames, as I imagine was done for iCub 2.5 .

I read this only now. Understood.

**Comment by prashanthr05** [comment]
With @FabioBergonti, we modified the visual and collision geometries for all the feet using data from the CAD,

```
  <link name="r_foot_front">
   ...
    <visual>
      <origin xyz="0.0 0.0 0.003" rpy="0 0 0"/>
      <geometry>
        <box size="0.117 0.100 0.006"/>
      </geometry>
      ...
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.003" rpy="0 0 0"/>
      <geometry>
        <box size="0.117 0.100 0.006"/>
      </geometry>
    </collision>
  </link>
```

On loading the model, we see
| View 1| View 2| 
|:---:|:--:|
|![Screenshot from 2020-11-06 11-41-11](https://user-images.githubusercontent.com/6506093/98358221-a8eecb00-2026-11eb-883e-c670161a463f.png)| ![Screenshot from 2020-11-06 11-52-06](https://user-images.githubusercontent.com/6506093/98358239-af7d4280-2026-11eb-8336-6539dfb10039.png)|

**Comment by S-Dafarra** [comment]
Great @prashanthr05! From the ``gif`` it seems a little tilted. Is it only my impression? You can also try to use the ``fixed`` version to look at the feet from below

**Comment by prashanthr05** [comment]
> Great @prashanthr05! From the `gif` it seems a little tilted. Is it only my impression? You can also try to use the `fixed` version to look at the feet from below

It is indeed tilted because of my poor camera skills ;D.

I tried loading the `fixed` version in vain. It keeps falling to the ground. 
The SDF format seems to be the same as fixed models in  `icub-gazebo`, while those in `icub-gazebo` remain fixed, instead those in `icub-models` don't. Is it just me who is facing this?

**Comment by traversaro** [comment]
This seems to be related to the base_link / root_link change .

**Comment by prashanthr05** [comment]
> This seems to be related to the base_link / root_link change .

Wow, such a memory! I am going to check this. Thanks, @traversaro !

**Comment by prashanthr05** [comment]
> This seems to be related to the base_link / root_link change .

I confirm. Changing the fixed joint child from `base_link` to `root_link`, makes it work.
```
    <joint name="fixed_base" type="fixed">
      <parent>world</parent>
      <child>iCub::root_link</child>
    </joint>
```

![Screenshot from 2020-11-06 12-49-22](https://user-images.githubusercontent.com/6506093/98362992-88c30a00-202e-11eb-80d9-49b6334d22bc.png)

**Comment by prashanthr05** [comment]
With the fixed model, 
|View 1| View 2| View 3 |
|:--:|:--:|:--:|
|![Screenshot from 2020-11-06 12-59-49](https://user-images.githubusercontent.com/6506093/98363943-210dbe80-2030-11eb-8d5c-c5ba886af381.png)|![Screenshot from 2020-11-06 12-59-19](https://user-images.githubusercontent.com/6506093/98363951-25d27280-2030-11eb-9867-db575591ea03.png)|![Screenshot from 2020-11-06 12-58-27](https://user-images.githubusercontent.com/6506093/98363959-2a972680-2030-11eb-9099-904c481f22e2.png)|

**Comment by prashanthr05** [comment]
I will open relevant PRs in the `icub-model-generator`.

**Comment by prashanthr05** [comment]
> > > I tried loading the fixed version in vain. It keeps falling to the ground.
> > > The SDF format seems to be the same as fixed models in icub-gazebo, while those in icub-gazebo remain fixed, instead those in icub-models don't. Is it just me who is facing this?
> > 
> > 
> > This seems to be related to the base_link / root_link change .
> 
> I confirm. Changing the fixed joint child from `base_link` to `root_link`, makes it work.
> 
> ```
>     <joint name="fixed_base" type="fixed">
>       <parent>world</parent>
>       <child>iCub::root_link</child>
>     </joint>
> ```

This has already been done in https://github.com/robotology/icub-models/pull/59.

**Comment by S-Dafarra** [comment]
Indeed, also to me the old fixed ``iCubV3`` falls down, but the ``iCubGazeboV3`` does not.

**Comment by prashanthr05** [comment]
To introduce the changes of assigned collision geometries from [here](https://github.com/robotology/icub-models/issues/66#issuecomment-723016671) to the URDF model through `icub-model-generator`, I will list the steps I will follow, please correct me wherever applicable
- Introduce an option for ICUB3 in the cmake options [here](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L6).
- Similar to what is done for ICUBPLUS robots of choosing between [two collision geometries](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L95), I add a conditional block for the ICUBTHREE collision geometries and pass that option to the [`generate_icub_simmechanics`](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L284) macro.
- Further, similar to what is done for ICUB25 models in [yaml options](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/data/icub2_5/ICUB_2-5_BB_simmechanics_options.yaml.in#L930) I add the relevant `@ASSIGNED_COLLISION_GEOMETRIES@` in [ICUB_3_all_options_gazebo.yaml](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/data/icub3/ICUB_3_all_options_gazebo.yaml).
Which will actually be handled by [`simmechanics-to-urdf`](https://github.com/robotology/simmechanics-to-urdf/blob/386e2c9c809d8d95e8e6c169cc23747de58ebae3/simmechanics_to_urdf/firstgen.py#L1079).

**Comment by S-Dafarra** [comment]
> To introduce the changes of assigned collision geometries from [here](https://github.com/robotology/icub-models/issues/66#issuecomment-723016671) to the URDF model through `icub-model-generator`, I will list the steps I will follow, please correct me wherever applicable
> 
> * Introduce an option for ICUB3 in the cmake options [here](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L6).
> * Similar to what is done for ICUBPLUS robots of choosing between [two collision geometries](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L95), I add a conditional block for the ICUBTHREE collision geometries and pass that option to the [`generate_icub_simmechanics`](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/CMakeLists.txt#L284) macro.
> * Further, similar to what is done for ICUB25 models in [yaml options](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/data/icub2_5/ICUB_2-5_BB_simmechanics_options.yaml.in#L930) I add the relevant `@ASSIGNED_COLLISION_GEOMETRIES@` in [ICUB_3_all_options_gazebo.yaml](https://github.com/robotology/icub-model-generator/blob/5f1ccfe8031fa2bbcd341c83fd85a10a93b381bf/simmechanics/data/icub3/ICUB_3_all_options_gazebo.yaml).
>   Which will actually be handled by [`simmechanics-to-urdf`](https://github.com/robotology/simmechanics-to-urdf/blob/386e2c9c809d8d95e8e6c169cc23747de58ebae3/simmechanics_to_urdf/firstgen.py#L1079).

@pattacini @Nicogene what do you think?

**Comment by prashanthr05** [comment]
Tested locally with changes made in https://github.com/prashanthr05/icub-model-generator/commit/d151943dad14ea87a9e644184a86d2dcce1828fa


The diff between the files with the introduced option and without,
```
<       <origin xyz="0.0 0.0 0.003" rpy="0.0 0.0 0.0"/>
---
>       <origin xyz="0.010700000000000012 -0.06475000000001183 0.9464469999999995" rpy="0 0 -1.57079632679"/>
250c250
<         <box size="0.117 0.1 0.006"/>
---
>         <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_l_foot_rear_prt.stl" scale="0.001 0.001 0.001"/>
283c283
<       <origin xyz="0.0 0.0 0.003" rpy="0.0 0.0 0.0"/>
---
>       <origin xyz="-0.10854999999999998 -0.06475000000001183 0.9464469999999995" rpy="0 0 -1.57079632679"/>
285c285
<         <box size="0.117 0.1 0.006"/>
---
>         <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_l_foot_front_prt.stl" scale="0.001 0.001 0.001"/>
1202c1202
<       <origin xyz="0.0 0.0 0.003" rpy="0.0 0.0 0.0"/>
---
>       <origin xyz="-0.10850000000000011 0.06484999999993908 0.9464470000000105" rpy="0 0 -1.57079632679"/>
1204c1204
<         <box size="0.117 0.1 0.006"/>
---
>         <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_r_foot_front_prt.stl" scale="0.001 0.001 0.001"/>
1230c1230
<       <origin xyz="0.0 0.0 0.003" rpy="0.0 0.0 0.0"/>
---
>       <origin xyz="0.010749999999999881 0.0648499999999391 0.9464470000000105" rpy="0 0 -1.57079632679"/>
1232c1232
<         <box size="0.117 0.1 0.006"/>
---
>         <mesh filename="package://iCub/meshes/simmechanics/sim_icub3_r_foot_rear_prt.stl" scale="0.001 0.001 0.001"/>

```



P.S. I had to test by disabling `GENERATE_DH_MODELS` and `tests`. See https://github.com/robotology/icub-model-generator/issues/161 and https://github.com/robotology/icub-model-generator/pull/159

cc @traversaro

**Comment by traversaro** [comment]
> P.S. I had to test by disabling GENERATE_DH_MODELS and tests. See robotology/icub-model-generator#161 and robotology/icub-model-generator#159 

Yes, that is expected.

**Comment by prashanthr05** [comment]
Given the merge of https://github.com/robotology/icub-model-generator/pull/165, shall we close this issue?

**Comment by traversaro** [comment]
Ok!
