### ISSUE TITLE
Rebase devel on master

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#80]
Right now devel is not on top of master. This cause problems when we want to test ros packages with along with iCub3 model

![image](https://user-images.githubusercontent.com/16744101/102634596-52f76200-4152-11eb-9b91-7f242ecca75a.png)

In details we would like have https://github.com/robotology/icub-models/pull/78 also on devel

cc @Yeshasvitvs @prashanthr05 @lrapetti @S-Dafarra @kouroshD

**Comment by traversaro** [comment]
Sorry, my fault. I will do it now.

**Comment by traversaro** [comment]
Done in https://github.com/robotology/icub-models/commit/ba5444390e8b5ea224dca16eeb7d63398001985e .
